[package]
name = "sync_tools"
version = "0.1.0"
edition = "2021"
description = "Some usefull tools to synchronise threads using tokio"
license = "MIT/Apache-2.0"

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
